apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-app-k8s
    labels:
        app: go-app-k8s
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-app-k8s
    template:
        metadata:
            labels:
                app: go-app-k8s
        spec:
            containers:
            -   name: go-app-k8s
                image: go-app-k8s
                imagePullPolicy: Never
                ports:
                -   containerPort: 8080